
name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t snaveed1/nodejs-project
    - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin 
    - run: docker push ${{secrets.DOCKERHUB_USERNAME}}/nodejs-project:latest
    - run: docker run -d -p 300:3000 {{secrets.DOCKERHUB_USERNAME}}/nodejs-project
